{% set name = "ompi-cuda" %}
{% set ompiVersion = "4.0.1" %}
{% set ompiVersionShort = "4.0" %}
{% set cudaVersion = '.'.join(environ.get('CUDA_VERSION', '9.2').split('.')[:2]) %}

package:
  name: {{ name }}
  version: {{ ompiVersion }}

source:
  - url: https://download.open-mpi.org/release/open-mpi/v{{ ompiVersionShort }}/openmpi-{{ ompiVersion }}.tar.gz
    folder: ompi

build:
  number: 0
  noarch: generic
  string: cuda{{ cudaVersion }}

requirements:
  build:
    - ca-certificates
    - cmake
    - git
    - make
    - zlib
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  run:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

test:
  commands:
    - mpiexec --version
    - orte-info

about:
  home: https://www.open-mpi.org/
  license: BSD-3
  doc_url: https://www.open-mpi.org/
  dev_url: https://www.open-mpi.org/
  summary: "CUDA-aware OpenMPI package w/o UCX"

extra:
  recipe-maintainers:
    - teju85
